# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      day: "saturday"
      time: "10:10"
      interval: "weekly"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus*"
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "saturday"
      time: "10:20"
      interval: "weekly"
    groups:
      gh-actions:
        patterns:
          - "*"