# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      #- ./src:/usr/src/app/src
      #- ./docs:/usr/src/app/docs
      #- ./static:/usr/src/app/static
      - docusaurus:/usr/src/app/.docusaurus
      - node_modules:/usr/src/app/node_modules
    develop:
      watch:
        - path: ./docs
          target: /usr/src/app/docs
          action: sync
        - path: ./src
          target: /usr/src/app/src
          action: sync
        - path: ./static
          target: /usr/src/app/static
          action: sync
            
volumes:
  docusaurus:
  node_modules:
