name: PR Build Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build website
        uses: ./.github/actions/docusaurus-build
